version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reservation_postgres
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - reservation_network

  redis:
    image: redis:7-alpine
    container_name: reservation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reservation_network

  adminer:
    image: adminer
    container_name: reservation_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - reservation_network

volumes:
  postgres_data:
  redis_data:

networks:
  reservation_network:
    driver: bridge
